### ISSUE TITLE
[CRASH] TypeError : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ChuDeSninStvO** [EliteMasterEric/Teyvat.moe#299]
**Describe the crash**

**Steps To Produce**

**Screenshots**

**Device Specs (please complete the following information):**

- App Version: [see options tab, e.g. 0.8.4]
- Device: [e.g. iPhone6, PC, Pixel 4a]
- OS: [e.g. iOS8.1, Android 11, Windows 10]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Error Message**

```

TypeError : Cannot read property '0' of undefined
at https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2764695
    at w (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530)
    at div
    at https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4809911
    at vo (https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2732862)
    at div
    at https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4809911
    at https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2791100
    at w (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530)
    at div
    at w (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530)
    at f (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:245430)
    at e (https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2681790)
    at https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4805772
    at https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:243614
    at HelmetProvider (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:431044)
    at t.a (https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4804880)

```

**Comment by EliteMasterEric** [comment]
@ChuDeSninStvO Could you try going to https://genshin-map-beta.netlify.app/ to see if you get this error there?

**Comment by EliteMasterEric** [comment]
@ChuDeSninStvO Please visit https://genshin-map-beta.netlify.app/ and verify that the app functions there. If it does not, please submit an error report as a new issue.
