### ISSUE TITLE
[BUG] TypeError: e.popupTitle is undefined

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#300]
**Describe the bug**

Open beta site, and this error shows.

TypeError: e.popupTitle is undefined

at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at Qn (components/interface/BorderBox.js:36:6)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at Zn (components/interface/Tabs.js:19:76)
    at xi< (components/views/controls/editor/MapControlsEditor.js:26:85)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at Qn (components/interface/BorderBox.js:36:6)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at fu< (components/views/controls/MapControls.js:116:35)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
    at _ref (../node_modules/react-redux/es/components/Provider.js:7:14)
    at e (components/views/error/ErrorHandler.js:18:21)
    at props (../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:54:24)
    at props (../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:48:24)
    at _this (../../src/Provider.js:55:4)
    at props (../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:32:17)

**To Reproduce**

Open beta webpage.

**Device Specs (please complete the following information):**

- GenshinMap app version: [see options tab, e.g. 'App version: 0.8.4']
- Device: PC
- OS: Windows 10
- Browser: Firefox
- Browser Version: 85.0 (64 bit)

**Comment by EliteMasterEric** [comment]
Sorry for the trouble. There appear to be a lot of issues with the rollout of the changes I've made over the past month.

Thankfully, with the most recent version I have drastically improved the error reporting, and with this stack trace, I believe I may know what the issue is.

Note, in the future please scroll down and click "Submit GitHub Issue", as this will attempt to retrieve other helpful information about the crash and generate an issue for you.

**Comment by EliteMasterEric** [comment]
@sgtoutlaw Please visit https://genshin-map-beta.netlify.app/ and verify that the app functions there. If it does not, please submit an error report as a new issue.
