### ISSUE TITLE
[CRASH] TypeError : e is null

### ISSUE THREAD

**Issue by stayvery** [EliteMasterEric/Teyvat.moe#302]
**Describe the crash**

**Steps To Produce**

**Screenshots**

**Device Specs (please complete the following information):**

- App Version: [see options tab, e.g. 0.8.4]
- Device: [e.g. iPhone6, PC, Pixel 4a]
- OS: [e.g. iOS8.1, Android 11, Windows 10]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Error Message**

```

TypeError : e is null
t@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:412058
Ke<@https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2717398
w@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530
Pe<@https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2719992
w@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530
div
f@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4791537
w@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530
div
w@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:247530
f@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:245428
e@https://genshinmap.github.io/static/js/main.47603ad3.chunk.js:1:2681790
t.a<@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4805770
u/</C<@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:243612
t@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:431044
t.a@https://genshinmap.github.io/static/js/2.70cf55f4.chunk.js:2:4804878

```

**Comment by stayvery** [comment]
I was creating a route and encountered this error. Anytime I attempt to open the editor it crashes now.

**Comment by EliteMasterEric** [comment]
I have diagnosed this issue already, and have been developing a fix.

Among other things, in the future, a crash in the editor tab will now only crash that tab instead of the entire app.

**Comment by EliteMasterEric** [comment]
@stayvery Please see if https://genshin-map-beta.netlify.app/ works for you.

**Comment by stayvery** [comment]
I opened your link MasterEric and got this error

Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>

at props (../node_modules/react-leaflet-markercluster/node_modules/@react-leaflet/core/esm/component.js:9:19)
    at hn (components/views/map/layers/MapCluster.js:76:90)
    at dn< (components/views/map/layers/FeatureLayer.js:24:6)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at f (../node_modules/react-leaflet/esm/MapContainer.js:35:3)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
    at _ref (../node_modules/react-redux/es/components/Provider.js:7:14)
    at e (components/views/error/ErrorHandler.js:18:21)
    at props (../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:54:24)
    at props (../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:48:24)
    at _this (../../src/Provider.js:55:4)
    at props (../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:32:17)

**Comment by EliteMasterEric** [comment]
@stayvery Apologies, but the link I sent you was apparently an old version that did not have the proper fixes deployed.

Please check that page to see if the issues are resolved.

**Comment by EliteMasterEric** [comment]
This issue was fixed back in February. It is caused when the app tries to use two different versions of react leaflet at the same time.
