### ISSUE TITLE
[CRASH] TypeError : je[t] is undefined

### ISSUE THREAD

**Issue by hey2022** [EliteMasterEric/Teyvat.moe#321]
**Describe the crash**

Can't show Liyue nature section and Liyue routes (same error appears)

**Steps To Produce**

1. Go to the beta site
2. Click on Features tab
3. Click on Liyue
4. Click on the natures section
5. See error

Or

1. Go to the beta site
2. Click on Routes tab
3. Click on Liyue

**Screenshots**

**Device Specs (please complete the following information):**

- App Version: [0.11.0]
- Device: [PC]
- OS: [Ubuntu 20.04]
- Browser: [Firefox]
- Browser Version: [85.0.1 (64-bit)]

**Additional context**

**Error Message**

```

TypeError : je[t] is undefined
    at ru< (components/views/controls/features/MapControlsRoutes.js:12:78)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at en (components/interface/BorderBox.js:36:6)
div
    at props (../node_modules/@material-ui/styles/esm/styled/styled.js:80:21)
    at es< (components/views/controls/MapControls.js:117:35)
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
div
    at useMemo (../node_modules/react-redux/es/components/connectAdvanced.js:218:21)
    at _ref (../node_modules/react-redux/es/components/Provider.js:7:14)
    at p (components/views/error/ErrorHandler.js:21:21)
    at props (../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:54:24)
    at props (../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:48:24)
    at _this (../../src/Provider.js:55:4)
    at props (../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:32:17)

```

**Current User Preferences**

```

R01fMDA3fnsidmVyc2lvbiI6IkdNXzAwNyIsIm9wdGlvbnMiOnsiY29tcGxldGVkQWxwaGEiOjAuNSwiY2x1c3Rlck1hcmtlcnMiOnRydWUsIndvcmxkQm9yZGVyRW5hYmxlZCI6dHJ1ZSwicmVnaW9uTGFiZWxzRW5hYmxlZCI6dHJ1ZSwiaGlkZUZlYXR1cmVzSW5FZGl0b3IiOmZhbHNlLCJoaWRlUm91dGVzSW5FZGl0b3IiOmZhbHNlLCJvdmVycmlkZUxhbmciOiIifSwiZGlzcGxheWVkIjp7ImZlYXR1cmVzIjp7Im1vbmRzdGFkdEFuZW1vY3VsdXMiOnRydWUsIm1vbmRzdGFkdFRlbGVwb3J0ZXIiOnRydWUsIm1vbmRzdGFkdFN0YXR1ZSI6dHJ1ZSwibW9uZHN0YWR0RG9tYWluIjp0cnVlLCJsaXl1ZUdlb2N1bHVzIjp0cnVlLCJsaXl1ZVRlbGVwb3J0ZXIiOnRydWUsImxpeXVlU3RhdHVlIjp0cnVlLCJsaXl1ZURvbWFpbiI6dHJ1ZSwiZHJhZ29uc3BpbmVDcmltc29uQWdhdGUiOnRydWUsImRyYWdvbnNwaW5lVGVsZXBvcnRlciI6dHJ1ZSwiZHJhZ29uc3BpbmVTdGF0dWUiOnRydWUsImRyYWdvbnNwaW5lRG9tYWluIjp0cnVlLCJtb25kc3RhZHRBcHBsZSI6ZmFsc2UsIm1vbmRzdGFkdFJ1aW5HdWFyZCI6ZmFsc2UsImxpeXVlSGlsaWNodXJsIjpmYWxzZSwibGl5dWVSdWluR3VhcmQiOmZhbHNlLCJtb25kc3RhZHRGYXR1aVNraXJtaXNoZXIiOmZhbHNlLCJtb25kc3RhZHRGYXR1aUVsZWN0cm9DaWNpbk1hZ2UiOmZhbHNlLCJtb25kc3RhZHRBYnlzc01hZ2UiOmZhbHNlLCJtb25kc3RhZHRTbGltZSI6dHJ1ZSwiZHJhZ29uc3BpbmVGYXR1aVNraXJtaXNoZXIiOnRydWUsImxpeXVlUWluZ3hpbiI6dHJ1ZSwibW9uZHN0YWR0V2hvcHBlcmZsb3dlciI6dHJ1ZSwibGl5dWVHZW9jdWx1c1Rlc3QiOmZhbHNlfSwicm91dGVzIjp7fX0sImNvbXBsZXRlZCI6eyJmZWF0dXJlcyI6eyJtb25kc3RhZHRBbmVtb2N1bHVzL0U1QkI5MjREQkE1MTFBRUZFQTdCNDFCOEE4NEEzRTZBQTAwNEU2NzciOjE2MTI1ODkwNzh9fSwiZWRpdG9yIjp7ImZlYXR1cmUiOnsibmFtZSI6IiIsImNhdGVnb3J5IjoiIiwicmVnaW9uIjoiIiwiZGF0YSI6W119fX0=

```

**Comment by EliteMasterEric** [comment]
It appears that one of the Liyue Nature data files is broken. I'm working on fixing it now for v0.11.1.

**Comment by EliteMasterEric** [comment]
Resolved.
